version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: beacon_usr
      POSTGRES_PASSWORD: beacon_pw
      POSTGRES_DB: beacon_db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  testdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: beacon_usr
      POSTGRES_PASSWORD: beacon_pw
      POSTGRES_DB: beacon_db
    ports:
      - 5433:5432
    volumes:
      - testdb-data:/var/lib/postgresql/data

volumes:
  db-data:
  testdb-data: